services: 
  postgres-db: 
    image: postgres:16.3
    container_name: batako-db
    environment: 
      POSTGRES_USER: batako_user
      POSTGRES_PASSWORD: batako_password_123
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports: 
      - "5432:5432"

volumes: 
  postgres-data: 
