CREATE TABLE IF NOT EXISTS transactions(
    id VARCHAR(36) PRIMARY KEY,
    quantity INTEGER NOT NULL,
    total_price DOUBLE PRECISION NOT NULL,
    purchase_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);