CREATE TABLE IF NOT EXISTS productions(
    id VARCHAR(36) PRIMARY KEY,
    quantity INTEGER NOT NULL,
    cement_used DOUBLE PRECISION NOT NULL,
    sand_used DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);